name: mingw-w64-gcc-git

on:
  workflow_dispatch:

jobs:
  mingw-w64-gcc-git:
    runs-on: windows-2022
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
      shell: bash        
    - name: Checkout repo
      uses: eko5624/checkout@v2      
    - name: Activate native windows symlinks
      run: | 
        sed -i 's/rem set MSYS=winsymlinks:nativestrict/set MSYS=winsymlinks:nativestrict/g' /c/msys64/msys2_shell.cmd
    - name: build 
      run: |                     
        C:\msys64\usr\bin\bash -lc 'pacman -S base-devel git mingw-w64-x86_64-toolchain mingw-w64-ucrt-x86_64-crt mingw-w64-ucrt-x86_64-headers mingw-w64-ucrt-x86_64-gcc --noconfirm' 
        C:\msys64\usr\bin\bash -lc 'git config --global user.email "example@example.com"'
        C:\msys64\usr\bin\bash -lc 'git config --global user.name "GitHub Actions"'
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-mcfgthread-git-r528.6af5465-1-any.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-mcfgthread-libs-git-r528.6af5465-1-any.pkg.tar.zst
        C:\msys64\usr\bin\bash -lc "pacman -U /d/a/mcfgthread/mcfgthread/*.tar.* --noconfirm"      
        C:\msys64\usr\bin\bash -lc 'cd /d/a/mcfgthread/mcfgthread/mingw-w64-gcc-git; MINGW_ARCH=ucrt64 makepkg-mingw -sLf'
    - name: Delete
      uses: eko5624/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: mingw-w64-ucrt-x86_64-gcc-git*
        fail-if-no-assets: false
        fail-if-no-release: false 
    - name: Upload
      uses: eko5624/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mingw-w64-gcc-git/*.tar.*
        tag: latest
        overwrite: true
        file_glob: true        
            
